# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    - go mod tidy
    
builds:
  - env:
      - CGO_ENABLED=0
    
    goos:
      - linux
      - windows

    goarch:
      - amd64
      - arm64
      - arm
      - 386

    ignore:
      - goos: windows
        goarch: arm
    
archives:
  -
    wrap_in_directory: true

    format_overrides:
      - goos: windows
        format: zip

    files:
      - LICENSE
    
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
